In [2]:
import torch
torch.cuda.current_device

<function torch.cuda.current_device() -> int>

In [4]:
torch.cuda.is_available()

False

In [5]:
torch.cuda.memory_allocated()

0

In [6]:
torch.cuda.memory_cached()

C:\Users\amii9\AppData\Local\Temp\ipykernel_21216\3499522927.py:1: FutureWarning: `torch.cuda.memory_cached` has been renamed to `torch.cuda.memory_reserved`
  torch.cuda.memory_cached()


0

### Dataset with pytorch

In [7]:
import torch
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df.shape

(150, 6)

In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

#chia dữ liệu với test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train_train = torch.LongTensor(y_train).reshape(-1,1)
y_test_test = torch.LongTensor(y_test).reshape(-1,1)

In [11]:
print("train size ", len(y_train))

train size  120


In [12]:
labels, counts = np.unique(y_train, return_counts=True)
print(labels, counts)

[0 1 2] [40 41 39]


In [ ]:
 #Tính đạo hàm n=bằng pytorch
def new_func():
    #cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
    #Tính y
    x = torch.tensor(2.0, requires_grad=True)
    y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1    
    print(y)
    y.backward()
    print(x.grad)
   


new_func()

tensor(63., grad_fn=<AddBackward0>)
tensor(93.)


In [15]:
import torch 
#Tao mot tensor voi requirments_grad duoc dat thanh true
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)


tensor(2., requires_grad=True)
None


In [16]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [18]:
y.grad_fn

In [19]:
y.backward()

In [20]:
x.grad

tensor(93.)

In [21]:
import torch
# Bài tập 
# Tính y = 5x^6 + 3x^3 + 2x^1 + x + 2x + 5x^4 + 1
# Cho biết độ dốc của đa thức trên tại điểm nào.
x = torch.tensor(2.0, requires_grad=True)
y = 5*x**6 + 3*x**3 + 2*x + x + 2*x + 5*x**4 + 1  # Chỉnh sửa công thức để đúng với đề bài
print(f"Giá trị của y: {y.item()}")

# Tính gradient
y.backward()
print(f"Độ dốc của đa thức tại x = 2: {x.grad.item()}")

Giá trị của y: 435.0
Độ dốc của đa thức tại x = 2: 1161.0


In [35]:
#BTVN
import torch

# Tạo tensor x với giá trị ban đầu là 2.0 và yêu cầu tính gradient
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
def y(x):
    return x**3 + 2*x**2 + 5*x + 1

# Tính y tại x = 2.0
y_val = y(x)

# Tính gradient của y theo x
y_val.backward()

# In gradient dy/dx tại x = 2.0
print("dy/dx tại x = 2.0:", x.grad)

# Gradient Descent
alpha = 0.1  # Learning rate
num_iterations = 10  # Số vòng lặp

for i in range(num_iterations):
    # Reset gradient trước mỗi vòng lặp
    if x.grad is not None:
        x.grad.zero_()
    
    # Tính giá trị của hàm số tại x hiện tại
    y_val = y(x)
    
    # Tính gradient
    y_val.backward()
    
    # Cập nhật x bằng Gradient Descent
    with torch.no_grad():  # Tắt tính gradient trong quá trình cập nhật
        x -= alpha * x.grad
    
    print(f"Lần {i+1}: x = {x.item()}, dy/dx = {x.grad.item()}")

print("Giá trị x sau 10 vòng lặp:", x.item())



dy/dx tại x = 2.0: tensor(25.)
Lần 1: x = -0.5, dy/dx = 25.0
Lần 2: x = -0.875, dy/dx = 3.75
Lần 3: x = -1.2546875476837158, dy/dx = 3.796875
Lần 4: x = -1.7250847816467285, dy/dx = 4.703972339630127
Lần 5: x = -2.427826166152954, dy/dx = 7.027413368225098
Lần 6: x = -3.7249975204467773, dy/dx = 12.971714973449707
Lần 7: x = -6.897680282592773, dy/dx = 31.726829528808594
Lần 8: x = -18.912006378173828, dy/dx = 120.14325714111328
Lần 9: x = -119.14640808105469, dy/dx = 1002.3439331054688
Lần 10: x = -4330.74755859375, dy/dx = 42116.01171875
Giá trị x sau 10 vòng lặp: -4330.74755859375


In [ ]:
#BTVN 2
import torch
import numpy as np

# Tạo dữ liệu giả
np.random.seed(42)  # Để đảm bảo tính nhất quán
X = np.random.uniform(1, 10, 100)  # 100 giá trị ngẫu nhiên từ 1 đến 10
noise = np.random.normal(0, 1, 100)  # 100 giá trị nhiễu ngẫu nhiên
Y = 3 * X + 5 + noise  # Y = 3X + 5 + noise

# Chuyển đổi sang tensors
X = torch.tensor(X, dtype=torch.float32).reshape(-1, 1)
Y = torch.tensor(Y, dtype=torch.float32).reshape(-1, 1)

# 1. Khởi tạo tham số w và b
w = torch.randn(1, requires_grad=True, dtype=torch.float32)
b = torch.randn(1, requires_grad=True, dtype=torch.float32)

# 2. Hàm tính MSE
def mse_loss(Y_pred, Y):
    return torch.mean((Y_pred - Y)**2)

# Learning rate
alpha = 0.01
num_iterations = 100

# Vòng lặp huấn luyện
for i in range(num_iterations):
    # Dự đoán
    Y_pred = X @ w + b

    # Tính loss
    loss = mse_loss(Y_pred, Y)

    # Tính gradients
    loss.backward()

    # Cập nhật tham số
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad

    # Reset gradients
    w.grad.zero_()
    b.grad.zero_()

    if (i+1) % 10 == 0:
        print(f'Epoch {i+1}/{num_iterations}, Loss: {loss.item():.4f}')

print(f'w: {w.item():.3f}, b: {b.item():.3f}')

Epoch 10/100, Loss: 148.7448
Epoch 20/100, Loss: 142.0632
Epoch 30/100, Loss: 135.8994
Epoch 40/100, Loss: 130.2133
Epoch 50/100, Loss: 124.9678
Epoch 60/100, Loss: 120.1287
Epoch 70/100, Loss: 115.6646
Epoch 80/100, Loss: 111.5465
Epoch 90/100, Loss: 107.7474
Epoch 100/100, Loss: 104.2428
w: 2.164, b: 6.517


In [37]:
import torch 
import numpy as np


In [38]:
torch.__version__

'2.6.0+cpu'

In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
x = torch.from_numpy(arr)
print(x)


tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [26]:
print(x.dtype)

torch.int32


In [27]:
print(x.type())

torch.IntTensor


In [30]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2 

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [31]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [32]:
arr = np.arange(0.5)
x = torch.from_numpy(arr)
print(x)



tensor([0.], dtype=torch.float64)


In [34]:
arr[0] = 99
print(x)

tensor([99.], dtype=torch.float64)


In [ ]:
#BTVN3
#Giải thích lý do tại sao cho 2 trường hợp ở trên

# Trường hợp 1: Bài toán tìm cực trị của hàm số y = x^3 + 2x^2 + 5x + 1
# Mục tiêu: Tìm giá trị của x sao cho hàm số y đạt giá trị nhỏ nhất (cực tiểu).
# Giải thích:
#   - Gradient Descent là một thuật toán tối ưu hóa để tìm cực tiểu của một hàm số.
#   - Bằng cách tính đạo hàm (gradient) của hàm số tại một điểm, ta biết hướng mà hàm số tăng nhanh nhất.
#   - Gradient Descent di chuyển ngược hướng gradient (tức là hướng mà hàm số giảm nhanh nhất) để tìm cực tiểu.
#   - Learning rate (alpha) quyết định kích thước bước di chuyển trong mỗi lần cập nhật.
#   - Việc lặp lại quá trình này nhiều lần giúp x hội tụ về một giá trị gần với cực tiểu của hàm số.

# Trường hợp 2: Bài toán Linear Regression (Hồi quy tuyến tính)
# Mục tiêu: Tìm các tham số w (weight) và b (bias) sao cho đường thẳng y = w*x + b phù hợp nhất với dữ liệu.
# Giải thích:
#   - MSE (Mean Squared Error) là một hàm mất mát đo lường sự khác biệt giữa giá trị dự đoán và giá trị thực tế.
#   - Mục tiêu là giảm thiểu MSE, tức là làm cho các dự đoán của mô hình gần với giá trị thực tế nhất có thể.
#   - Gradient Descent được sử dụng để tìm các giá trị của w và b sao cho MSE đạt giá trị nhỏ nhất.
#   - Tương tự như trường hợp 1, đạo hàm của MSE theo w và b cho biết hướng cần điều chỉnh w và b để giảm MSE.
#   - Việc lặp lại quá trình này nhiều lần giúp w và b hội tụ về các giá trị tối ưu.

In [39]:
#BTVN4
import torch

# Empty tensor
empty_tensor = torch.empty(2, 3)
print("Empty Tensor:\n", empty_tensor)

# Zeros tensor
zeros_tensor = torch.zeros(2, 3)
print("\nZeros Tensor:\n", zeros_tensor)

# Ones tensor
ones_tensor = torch.ones(2, 3)
print("\nOnes Tensor:\n", ones_tensor)

# Random tensor
random_tensor = torch.rand(2, 3)
print("\nRandom Tensor:\n", random_tensor)

# Reshape tensor
original_tensor = torch.arange(12)
print("\nOriginal Tensor:\n", original_tensor)

# Reshape with view
reshaped_tensor_view = original_tensor.view(3, 4)
print("\nReshaped Tensor with view:\n", reshaped_tensor_view)

# Reshape with view_as
another_tensor = torch.zeros(3, 4)
reshaped_tensor_view_as = original_tensor.view_as(another_tensor)
print("\nReshaped Tensor with view_as:\n", reshaped_tensor_view_as)

Empty Tensor:
 tensor([[-3.6863e-18,  9.4307e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
 tensor([[0.2637, 0.1718, 0.6090],
        [0.6097, 0.9249, 0.0018]])

Original Tensor:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped Tensor with view:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped Tensor with view_as:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
